# Copyright 2016 Hewlett-Packard Development Company, L.P.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# END OF TERMS AND CONDITIONS

version: '2'
services:
  logger:
    #image: fluent/fluentd:v0.14.8
    build:
      context: ./fluentd
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - ftp_proxy=$ftp_proxy
        - no_proxy=$no_proxy
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - FTP_PROXY=$FTP_PROXY
        - NO_PROXY=$NO_PROXY

  kibana:
    environment:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - ftp_proxy=$ftp_proxy
        - no_proxy=${no_proxy},elastic
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - FTP_PROXY=$FTP_PROXY
        - NO_PROXY=${NO_PROXY},elastic
