version: '2'
services:
  myservice:
    build: ./myservice
    depends_on:
      - logger
    ports:
      - "3000:3000"
    volumes:
      - ./myservice:/usr/src/app
    networks:
      - logger_net
  logger:
    #image: fluent/fluentd:v0.14.8
    build:
      context: ./fluentd
    ports:
      - "24224:24224"
    depends_on:
      - elastic
    volumes:
      - ./conf:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluentd.conf
    networks:
      - logger_net
  elastic:
    image: elasticsearch:2.4.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - logger_net
  kibana:
    image: kibana:4.6.1
    ports:
      - "5601:5601"
    depends_on:
      - elastic
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    networks:
      - logger_net
networks:
  logger_net:
