version: '2'
services:
  demo_service:
    build: ./demo_service
    depends_on:
      - logger
    ports:
      - "3000:3000"
    volumes:
      - ./demo_service:/usr/src/app
    networks:
      - logger_net

networks:
  logger_net:
